### ISSUE TITLE
Cannot get the user infomation

### ISSUE THREAD

**Issue by tharakabimal** [eventfly/eventfly#1]
Hi @sungwoncho,

Need your help to figure out what I'm doing wrong here. I have the following server [method](https://github.com/eventfly/eventfly/blob/master/server/methods/users.js) to register a user and assign that user to a role.

    Meteor.methods({
        'users.register'(username, password) {

    	    var _id;

    	    check(username, String);
    	    check(password, String);

		_id = Accounts.createUser({
			email: username,
			password: password
		});

		Roles.addUsersToRoles(_id, 'normal-user');

        }
      });

This works fine. But when I [publish](https://github.com/eventfly/eventfly/blob/master/server/publications/users.js) the current User information, I'm not getting any data on the [client](https://github.com/eventfly/eventfly/blob/master/client/modules/users/containers/user_header.js) side. What could be the reason for this?

**Comment by sungwoncho** [comment]
Your pub/sub look okay to me. Does `Accounts.createUser` complain that you need `profile`?

**Comment by tharakabimal** [comment]
No it does not complain. I moved the **Accounts.createUser** function from the server side [method](https://github.com/eventfly/eventfly/blob/master/server/methods/users.js#L13-L18) to the [client](https://github.com/eventfly/eventfly/blob/master/client/modules/users/actions/users.js#L27-L30) side. And now it works fine.

When I try to [publish](https://github.com/eventfly/eventfly/blob/master/server/publications/users.js#L6) the user details when the **Accounts.createUser** was on the server side, console.log says the usersId is null

**Comment by tharakabimal** [comment]
I just learnt that when **Accounts.createUser** is run on the server, it only returns the userId. It doesn't autopmatically login the user. So I created a call back on the client side and used Meteor.loginWithPassword. Thanks
